version: '3.9'

services:
  phosanalyticsapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: phosAnalyticsAPI
    environment:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
    ports:
      - "8080:8080"
    restart: unless-stopped

  ngrokpaapi:
    image: ngrok/ngrok:latest
    container_name: ngrokPhosAnalyticsAPI
    depends_on:
      - phosanalyticsapi
    environment:
      NGROK_AUTHTOKEN: "2vdGDQZh2sEm6YpziOroTQbkNYO_5FJFmNhxHsqK2iy6JsC9Q"
    command: http phosAnalytics:8080
    restart: unless-stopped
    profiles:
      - ngrokpaapi
